name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        package-dir: ['hello', 'integers', 'iteration', 'array', 'structs']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd ${{ matrix.package-dir }} && go build -v ./...

    - name: Test
      run: cd ${{ matrix.package-dir }} && go test -v ./...
